"""added a new field about the last otp requested time in otp table

Revision ID: 3b8310b16a3e
Revises: b8ec968da287
Create Date: 2025-08-19 11:08:34.590716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8310b16a3e'
down_revision: Union[str, Sequence[str], None] = 'b8ec968da287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('last_requested_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'last_requested_time')
    # ### end Alembic commands ###
